library(shiny)  
shinyUI(pageWithSidebar(headerPanel("IRON MAIDENS FTC #9205 RES-Q Point Calculator"),
                        sidebarPanel(width=3,
                                     h2('Total Points'),
                                     h4('Total Autonomous Period Points'),
                                     verbatimTextOutput("tot1"),
                                     h4('Total Driver-Controlled Period Points'),
                                     verbatimTextOutput("tot2"),
                                     h4('Total End Game Scoring'),
                                     verbatimTextOutput("tot3"),
                                     h3('Total Overall Points'),
                                     verbatimTextOutput("tot4")),
    mainPanel(width=6,h2('What Can Your Robot Do?'),h3('Autonomous Period'),
              numericInput("id1","Climbers In Shelter",0,min=0,max=2, step=1),   
              radioButtons("id2","Rescue Beacon Illuminated for Alliance",c("Yes"="20","No"="0")),
              radioButtons("id3","Where Will Your Robot Park? Select One:",
                  c("In the Field"="0",
                    "Rescue Beacon Repair Zone"="5",
                    "In a Floor Goal"="5",
                    "On the Mountain, Touching the Floor"="5",
                    "On the Mountain, Low Zone"="10",
                    "On the Mountain, Mid Zone"="20",
                    "On the Mountain, High Zone"="40"
                    )),
    h3('Driver-Controlled Period'),
    sliderInput(inputId="num1",label="Number of Debris Scored in a Floor Goal",value=0,min=0,max=50),
    sliderInput(inputId="num2",label="Number of Debris Scored in Mountain Low Zone Goal",value=0,min=0,max=10),
    sliderInput(inputId="num3",label="Number of Debris Scored in Mountain Mid Zone Goal",value=0,min=0,max=10),
    sliderInput(inputId="num4",label="Number of Debris Scored in Mountain High Zone Goal",value=0,min=0,max=10),
    radioButtons("id4","Where Will Your Robot Park? Select One:",
                 c("In the Field"="0",
                  "On the Mountain, Touching the Floor"="5",
                   "On the Mountain, Low Zone"="10",
                   "On the Mountain, Mid Zone"="20",
                   "On the Mountain, High Zone"="40")),
    numericInput("id5",'Climbers Released/Slid Down the Zip Line',0,min=0,max=3, step=1),
    numericInput("id6",'Climbers in a Shelter',0,min=0,max=2, step=1),
    
    h3('End Game'),
    radioButtons("id7","Robot Completely Supported by Pull-Up Bar",c("Yes"="80","No"="0")),
    radioButtons("id8","Claim an All-Clear Signal",c("Yes"="20","No"="0")),
    submitButton('Go!'))
))
